config/routes.php
<?php

use I18n\Lib\Lang;
use Cake\Core\Configure;
use Cake\Routing\Router;
use Cake\Network\Session;
use Cake\ORM\TableRegistry;
use Cake\Routing\RouteBuilder;
use Section\Routing\SectionsRoutes;
use Cake\Datasource\ConnectionManager;

Router::plugin(
    'Section',
    ['path' => '/{lang}/section'],
    function (RouteBuilder $routes) {
        $routes->fallbacks(DashedRoute::class);
    }
);

Router::plugin(
    'Section',
    ['path' => '/section'],
    function (RouteBuilder $routes) {
        $routes->fallbacks(DashedRoute::class);
    }
);

$argv = env('argv');

if (isset($argv[1]) && $argv[1] == 'migrations') {
    return;
}

$connection = ConnectionManager::get('default');

foreach (['sections', 'slugs', 'seos'] as $table) {
    $results = $connection->execute("SHOW TABLES LIKE '$table'")->fetchAll('assoc');

    if (empty($results)) {
        return;
    }
}

if (Configure::read('Installing')) {
    return;
}

Router::extensions(['xml']);

$sessionConfig = (array)Configure::read('Session') + [
    'defaults' => 'php',
];

$session = new Session($sessionConfig);


if (isset($_SERVER['REQUEST_URI']) && strpos($_SERVER['REQUEST_URI'], '.') === false && $session->read('Manager.preview')) {
    Configure::write('Manager.preview', true);
    $session->delete('Manager.preview');
}

session_write_close();

$SectionsTable = TableRegistry::getTableLocator()->get('Section.Sections');
$SectionsTable->removeBehavior('Blockable');
$query = $SectionsTable->find('nav')
    ->order('position');

if (!Configure::read('Manager.preview')) {
    $query->where(['Sections.published' => 1]);
}

$sections = $query->toArray();
TableRegistry::getTableLocator()->remove('Section.Sections');
SectionsRoutes::nestedRoutes($sections);
SectionsRoutes::dynamics();

Router::connect('/sitemap', [
    'plugin' => 'Section',
    'controller' => 'Sections',
    'action' => 'sitemap'
]);

src/Model/Entity/Link.php
<?php
namespace Section\Model\Entity;

use Manager\Model\Entity\CrudEntityTrait;
use Cake\ORM\Behavior\Translate\TranslateTrait;
use Cake\ORM\Entity;
use Cake\ORM\TableRegistry;

/**
 * Link Entity
 *
 * @property int $id
 * @property string $model
 * @property string $foreign_key
 * @property string $section_id
 * @property string $doc
 * @property int $position
 * @property string $type
 * @property string $url
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 */
class Link extends Entity
{
  use CrudEntityTrait;
  use TranslateTrait;

  /**
   * Fields that can be mass assigned using newEntity() or patchEntity().
   *
   * Note that when '*' is set to true, this allows all unspecified fields to
   * be mass assigned. For security purposes, it is advised to set '*' to false
   * (or remove it), and explicitly make individual fields accessible as needed.
   *
   * @var array
   */
  protected $_accessible = [
      '*' => true,
      'position' => false
  ];

  protected function _getLink()
  {
    $url = null;

    if( $this->type == 'section')
    {
      $url = TableRegistry::get( 'Section.Sections')->getUrl( $this->section_id);
    }
    elseif( $this->type == 'url')
    {
      $url = $this->url;
    }
    elseif( $this->type == 'doc')
    {
      $url = $this->doc->paths [0];
    }

    return $url;
  }
}

src/Template/Element/menu_template.ctp
<!-- Nested node template -->
<script type="text/ng-template" id="nodes_renderer.html">
  <div class="dd-handle cf-section-list-item">
    <span class="" ng-show="!collapsed && content.nodes.length > 0" style="width: 40px; margin-right: 10px; flex-grow: 0" ng-click="collapsed = !collapsed"><i class="fa fa-plus"></i></span>
    <span class="" ng-show="collapsed && content.nodes.length > 0" style="width: 40px; margin-right: 10px; flex-grow: 0" ng-click="collapsed = !collapsed"><i class="fa fa-minus"></i></span>

    <span title="{{ data.actionTypes[content.sectionType.key] }}" ui-tree-handle><i class="cf-section-icon {{ content.sectionType.icon }}"></i> {{ content.title }}</span> 
    <i ng-if="content.is_homepage == 1" class="fa fa-home"></i> <i title="<?= __d('admin', 'No publicado') ?>" ng-if="!content.published == 1" class="fa fa-remove"></i>
    <a class="pull-right btn btn-white btn-xs" ng-model="data" cf-modal="'/admin/section/sections/add/' + menu.menu.key + '/' + content.id" href><i class="fa fa-plus"></i></a>
    <a class="pull-right btn btn-white btn-xs" href confirm-delete cf-url="{{ content.urls.delete }}" cf-destroy="scope.contents.splice( scope.$index, 1)"><i class="fa fa-trash"></i></a> 
    <a title="{{ actionTypes[content.sectionType.key] }}" class="pull-right btn btn-white btn-xs" href="#admin/section/sections/update/{{ content.id }}"><i class="fa fa-pencil"></i></a>
  </div>
  <ol class="dd-list" ui-tree-nodes="" ng-model="content.nodes" ng-init="nodes = content.nodes" ng-show="collapsed">
    <li class="dd-item" ng-repeat="content in nodes" ng-init="contents = nodes" ui-tree-node ng-include="'nodes_renderer.html'">
    </li>
  </ol>
</script>

src/Template/Element/menu_tree.ctp
<div class="ibox-title">
  <h5>{{ menu.menu.title }}</h5>
</div>
<div class="ibox-content">
  <div ui-tree="treeOptions" class="dd cf-sections-list" data-max-depth="4" id="tree-root-{{ menu.menu.title }}">
    <ol class="dd-list" ui-tree-nodes="" ng-model="menu.contents">
      <li class="dd-item" ng-repeat="content in menu.contents" ui-tree-node ng-init="contents = menu.contents" ng-include="'nodes_renderer.html'"></li>
    </ol>
  </div>
  <a ng-model="data" cf-modal="'/admin/section/sections/add/' + menu.menu.key + '/0'" href class="btn btn-outline btn-default btn-xs m-t"><i class="fa fa-plus"></i> <span class="bold"><?= __d( 'admin', 'Añadir') ?></span></a>
</div>

src/Template/Element/webmap.ctp
<ul>
<?php foreach( $sections as $section): ?>
    <li><a href="<?= $section->link() ?>"><?= $section->title ?></a>
      <?php if( !empty( $section->children)): ?>
          <?= $this->element( 'webmap', ['sections' => $section->children]) ?>
      <?php endif ?>
    </li>
<?php endforeach ?>
</ul>